version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo-vehicles-backend
hook:
  ApplicationStop:
    - locaion: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - locaion: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
